### ISSUE TITLE
Currently using our beta JavaScript SDK

### ISSUE THREAD

**Issue by lukeocodes** [deepgram-starters/nextjs-live-transcription#1]
This demo is currently utilising our beta JavaScript SDK for the purposes of live transcription directly from the client. This version of the SDK is considered stable. It remains in beta while we endeavour to prepare all documentation and migration guides for the purposes of a production releases. You're welcome to track these changes on the repository itself. 

https://github.com/deepgram/deepgram-node-sdk

**Comment by dan7geo** [comment]
This does on work properly on iOS browsers including Safari. The live transcription works well for the first 10-20 seconds on iOS. Then it loses the websocket connection and says "Deepgram is connecting". After that it shows "Deepgram is connected" but stops working. No further captions are produced after this.

Whenever the websocket disconnects, the Close event seems to be triggered correctly because isListening is set to false. It seems a new websocket connection is also correctly established after this because isListening gets changed back to true. 

Not sure what's going wrong here just on iOS because this works well on android, windows, Mac.

**Comment by btahir** [comment]
Great work on this. Any update on this issue though? I'm even having this on my Mac. It works for a few seconds but then once the connection is established again the captions do not update.
